function [YEAR,QUARTER,Deltayt,Et1Deltayt1,pit,Et1pit1,it,Et1it1] = importfile1(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE1 Import data from a spreadsheet
%   [YEAR,QUARTER,Deltayt,Et1Deltayt1,pit,Et1pit1,it,Et1it1] =
%   IMPORTFILE1(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as column
%   vectors.
%
%   [YEAR,QUARTER,Deltayt,Et1Deltayt1,pit,Et1pit1,it,Et1it1] =
%   IMPORTFILE1(FILE,SHEET) reads from the specified worksheet.
%
%   [YEAR,QUARTER,Deltayt,Et1Deltayt1,pit,Et1pit1,it,Et1it1] =
%   IMPORTFILE1(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   [YEAR,QUARTER,Deltayt,Et1Deltayt1,pit,Et1pit1,it,Et1it1] = importfile1('PS2data.xlsx','Sheet1',53,192);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2016/11/23 13:26:16

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 53;
    endRow = 192;
end

%% Import the data
data = xlsread(workbookFile, sheetName, sprintf('A%d:H%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    tmpDataBlock = xlsread(workbookFile, sheetName, sprintf('A%d:H%d',startRow(block),endRow(block)));
    data = [data;tmpDataBlock]; %#ok<AGROW>
end

%% Allocate imported array to column variable names
YEAR = data(:,1);
QUARTER = data(:,2);
Deltayt = data(:,3);
Et1Deltayt1 = data(:,4);
pit = data(:,5);
Et1pit1 = data(:,6);
it = data(:,7);
Et1it1 = data(:,8);

