%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Francisco Ilabaca\Desktop\Macro\Advanced Macro\PS3\Canada_Policy_Uncertainty_Data.xlsx
%    Worksheet: Canadian News-Based Index
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/12/07 23:29:10

%% Import the data
[~, ~, raw] = xlsread('C:\Users\Francisco Ilabaca\Desktop\Macro\Advanced Macro\PS3\Canada_Policy_Uncertainty_Data.xlsx','Canadian News-Based Index','A2:C240');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,1);
raw = raw(:,[2,3]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Year = cellVectors(:,1);
Month = data(:,1);
can_ui = data(:,2);

%% Clear temporary variables
clearvars data raw cellVectors;

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread('C:\Users\Francisco Ilabaca\Desktop\Macro\Advanced Macro\PS3\can_cpi.xls','FRED Graph','A2:B220','',@convertSpreadsheetExcelDates);
raw = raw(:,2);
dates = dates(:,1);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
observation_date = datetime([dates{:,1}].', 'ConvertFrom', 'Excel', 'Format', 'MM/dd/yyyy');
can_cpi = data(:,1);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% observation_date=datenum(observation_date);

%% Clear temporary variables
clearvars data raw dates;

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread('C:\Users\Francisco Ilabaca\Desktop\Macro\Advanced Macro\PS3\can_ind.xls','FRED Graph','A2:B218','',@convertSpreadsheetExcelDates);
raw = raw(:,2);
dates = dates(:,1);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
observation_date1 = datetime([dates{:,1}].', 'ConvertFrom', 'Excel', 'Format', 'MM/dd/yyyy');
can_ind = data(:,1);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% observation_date1=datenum(observation_date1);

%% Clear temporary variables
clearvars data raw dates;

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread('C:\Users\Francisco Ilabaca\Desktop\Macro\Advanced Macro\PS3\can_ir.xls','FRED Graph','A2:B220','',@convertSpreadsheetExcelDates);
raw = raw(:,2);
dates = dates(:,1);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
observation_date2 = datetime([dates{:,1}].', 'ConvertFrom', 'Excel', 'Format', 'MM/dd/yyyy');
can_ir = data(:,1);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% observation_date2=datenum(observation_date2);

%% Clear temporary variables
clearvars data raw dates;