%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/dillonflannery-valadez/Google Drive/MATLAB/Year2/adv_macro/Hw3/Canada_Policy_Uncertainty_Data.xlsx
%    Worksheet: Canadian News-Based Index
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/12/08 21:07:19

%% Import the data
[~, ~, raw] = xlsread('/Users/dillonflannery-valadez/Google Drive/MATLAB/Year2/adv_macro/Hw3/Canada_Policy_Uncertainty_Data.xlsx','Canadian News-Based Index');
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,1);
raw = raw(:,[2,3]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Year2 = cellVectors(:,1);
Month2 = data(:,1);
uncertainty = data(:,2);

%% Clear temporary variables
clearvars data raw;
%% Import the data
[~, ~, raw] = xlsread('/Users/dillonflannery-valadez/Google Drive/MATLAB/Year2/adv_macro/Hw3/can_ir.xls','FRED Graph');
raw = raw(2:end,:);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
observation_date = data(:,1);
can_ir = data(:,2);
%% Clear temporary variables
clearvars data raw;
%% Import the data
[~, ~, raw] = xlsread('/Users/dillonflannery-valadez/Google Drive/MATLAB/Year2/adv_macro/Hw3/can_ind.xls','FRED Graph');
raw = raw(2:end,:);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
observation_date = data(:,1);
can_ind = data(:,2);

%% Clear temporary variables
clearvars data raw;
%% Import the data
[~, ~, raw] = xlsread('/Users/dillonflannery-valadez/Google Drive/MATLAB/Year2/adv_macro/Hw3/can_cpi.xls','FRED Graph');
raw = raw(2:end,:);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
observation_date = data(:,1);
can_cpi = data(:,2);

%% Clear temporary variables
clearvars data raw;