function [ alpha ] = mhAcceptPXW(Wstar, Dstar, Rstar, W0, D0,...
    R0, S, nu, Supdate, nuupdate, ...
    latentData, meanLatentData )

K = size(Rstar,1);
JacNum = .5*(K-1)*sum(log(diag(Dstar)));
JacDen = .5*(K-1)*sum(log(diag(D0)));
% surLL computes by row for every column!
Num = logWishart(Wstar, S, nu) + ...
    surLL(latentData, meanLatentData, Rstar) + JacNum + ...
    logWishart(W0, Supdate,nuupdate);
Den = logWishart(W0, S, nu) + ...
      surLL(latentData, meanLatentData, R0) + JacDen +...
       logWishart(Wstar, Supdate, nuupdate);     
alpha = min(0, Num - Den);

end

