function [ alpha ] = mhStepMvProbit(Wstar, Dstar, Rstar, W0, D0,...
    R0, wprior, wishartDf, latentData, meanLatentData) 
% surLL computes by row for every column!
Num = logpxWishart(Dstar,Rstar,wishartDf, wprior) + ...
      surLL(latentData,meanLatentData,Rstar) + ...
      logwish(W0, Wstar, wishartDf) ;
Den = logpxWishart(D0,R0,wishartDf, wprior) + ...
      surLL(latentData,meanLatentData,R0) + ...
      logwish(Wstar, W0, wishartDf);
%   [logpxWishart(Dstar,Rstar,wishartDf, wprior),...
%       surLL(latentData,meanLatentData,Rstar),...
%        logwish(W0, Wstar, wishartDf)]
%   [logpxWishart(D0,R0,wishartDf, wprior),...
%        surLL(latentData,meanLatentData,R0),...
%         logwish(W0, Wstar, wishartDf)]
alpha = min(0, Num - Den);
end

