%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/dillon4287/Datasets/international_probit_dataset.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/08/13 15:25:55

%% Initialize variables.
filename = '/home/dillon4287/Datasets/international_probit_dataset.csv';
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: datetimes (%{MM/dd/yyyy}D)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%{MM/dd/yyyy}D%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
internationalprobitdataset = table(dataArray{1:end-1}, 'VariableNames', {'date','realspusa','tedrateusa','tenmin3usa','tedratecanada','tenmin3canada','sptsecanada','recessionusa','recessioncanada'});

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% internationalprobitdataset.date=datenum(internationalprobitdataset.date);

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;